import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, Text, TextInput, View } from "react-native";
import Ionicons from "@react-native-vector-icons/ionicons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api/client";
import { EmptyState } from "@/src/components/EmptyState";
import { useToast } from "@/src/components/toast";
import { fontFamily, fontSize, makeStyles, radius, spacing, useTheme } from "@/src/theme";

type Item={id:string;name:string;category:string;size:string;quantity:number;unit:string;minimumStock:number};

export default function NewInventory(){
 const styles=useStyles(); const {colors}=useTheme(); const insets=useSafeAreaInsets(); const toast=useToast(); const qc=useQueryClient();
 const [category,setCategory]=useState("");
 const [name,setName]=useState("");
 const [size,setSize]=useState(""); const [qty,setQty]=useState(""); const [unit,setUnit]=useState("pcs"); const [min,setMin]=useState("0"); const [search,setSearch]=useState("");
 const q=useQuery<Item[]>({queryKey:["inventory"],queryFn:()=>api.get("/inventory")});
 const add=useMutation({mutationFn:()=>api.post("/inventory",{name,category,size,quantity:Number(qty),unit,minimumStock:Number(min)}),onSuccess:()=>{setName("");setCategory("");setSize("");setQty("");setUnit("pcs");setMin("0");qc.invalidateQueries({queryKey:["inventory"]});toast("Inventory item saved.","success");}});
 const list=useMemo(()=>{const s=search.trim().toLowerCase();return (q.data||[]).filter(x=>!s||x.name.toLowerCase().includes(s));},[q.data,search]);
 const submit=()=>{if(!name.trim()||!qty||Number(qty)<=0){toast("Enter an item name and quantity above 0.","error");return;}add.mutate();};
 return <View style={styles.container}>
  <View style={[styles.header,{paddingTop:insets.top+spacing.sm}]}>
   <Text style={styles.kicker}>STOCK MANAGEMENT</Text><Text style={styles.title}>New Inventory</Text><Text style={styles.subtitle}>Add implants and keep a live inventory list.</Text>
   <View style={styles.form}>
    <View style={styles.inputWrap}><Ionicons name="layers-outline" size={20} color={colors.muted}/><TextInput value={category} onChangeText={setCategory} placeholder="Category e.g. Interlocking Nail 10mm" placeholderTextColor={colors.muted} style={styles.input}/></View>
    <View style={styles.inputWrap}><Ionicons name="cube-outline" size={20} color={colors.muted}/><TextInput value={name} onChangeText={setName} placeholder="Item / implant name" placeholderTextColor={colors.muted} style={styles.input}/></View>
    <View style={styles.inputWrap}><Ionicons name="resize-outline" size={20} color={colors.muted}/><TextInput value={size} onChangeText={setSize} placeholder="Size / length e.g. 280mm" placeholderTextColor={colors.muted} style={styles.input}/></View>
    <View style={styles.two}><View style={[styles.inputWrap,{flex:1}]}><TextInput value={qty} onChangeText={setQty} placeholder="Quantity" placeholderTextColor={colors.muted} keyboardType="decimal-pad" style={styles.input}/></View><View style={[styles.inputWrap,{flex:1}]}><TextInput value={unit} onChangeText={setUnit} placeholder="Unit" placeholderTextColor={colors.muted} style={styles.input}/></View></View>
    <View style={styles.two}><View style={[styles.inputWrap,{flex:1}]}><TextInput value={min} onChangeText={setMin} placeholder="Minimum stock" placeholderTextColor={colors.muted} keyboardType="decimal-pad" style={styles.input}/></View><Pressable style={[styles.save,{flex:1},add.isPending&&styles.disabled]} onPress={submit} disabled={add.isPending}>{add.isPending?<ActivityIndicator color={colors.onBrandPrimary}/>:<><Ionicons name="add-circle-outline" size={20} color={colors.onBrandPrimary}/><Text style={styles.saveText}>Add Inventory</Text></>}</Pressable></View>
   </View>
  </View>
  <View style={styles.listHeader}><Text style={styles.sectionTitle}>Inventory List</Text><View style={styles.count}><Text style={styles.countText}>{list.length}</Text></View></View>
  <View style={styles.search}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Search items..." placeholderTextColor={colors.muted} style={styles.searchInput}/></View>
  {q.isLoading?<View style={styles.center}><ActivityIndicator size="large" color={colors.brandPrimary}/></View>:q.isError?<View style={styles.center}><EmptyState icon="cloud-offline-outline" title="Could not load inventory" subtitle="Refresh the local database and try again."/></View>:<FlatList data={list} keyExtractor={x=>x.id} contentContainerStyle={{padding:spacing.lg,paddingBottom:insets.bottom+spacing.xl,flexGrow:1}} refreshControl={<RefreshControl refreshing={q.isRefetching} onRefresh={q.refetch}/>} ListEmptyComponent={<EmptyState icon="cube-outline" title="No inventory items" subtitle="Add your first implant above."/>} renderItem={({item})=><View style={styles.row}><View style={styles.icon}><Ionicons name="cube" size={20} color={colors.brandPrimary}/></View><View style={{flex:1}}><Text style={styles.item}>{[item.category,item.name,item.size].filter(Boolean).join(" · ")}</Text><Text style={styles.meta}>{item.quantity} {item.unit} · Minimum {item.minimumStock}</Text></View><View style={[styles.badge,item.quantity<=item.minimumStock&&styles.badgeLow]}><Text style={[styles.badgeText,item.quantity<=item.minimumStock&&styles.badgeLowText]}>{item.quantity<=item.minimumStock?"LOW":"OK"}</Text></View></View>}/>}
 </View>;
}
const useStyles=makeStyles(colors=>({container:{flex:1,backgroundColor:colors.surfaceSecondary},header:{backgroundColor:colors.surface,paddingHorizontal:spacing.lg,paddingBottom:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.border},kicker:{fontFamily:fontFamily.semibold,fontSize:fontSize.xs,color:colors.brandPrimary,letterSpacing:1},title:{fontFamily:fontFamily.bold,fontSize:fontSize.xxl,color:colors.onSurface,marginTop:spacing.xs},subtitle:{fontFamily:fontFamily.regular,fontSize:fontSize.sm,color:colors.muted,marginTop:spacing.xs},form:{marginTop:spacing.lg,gap:spacing.sm},two:{flexDirection:"row",gap:spacing.sm},inputWrap:{minHeight:48,flexDirection:"row",alignItems:"center",gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:colors.surface},input:{flex:1,color:colors.onSurface,fontFamily:fontFamily.regular,fontSize:fontSize.base,paddingVertical:spacing.sm},save:{minHeight:48,borderRadius:radius.md,backgroundColor:colors.brandPrimary,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:spacing.xs},saveText:{fontFamily:fontFamily.semibold,color:colors.onBrandPrimary,fontSize:fontSize.sm},disabled:{opacity:.6},listHeader:{paddingHorizontal:spacing.lg,paddingTop:spacing.lg,flexDirection:"row",alignItems:"center",gap:spacing.sm},sectionTitle:{fontFamily:fontFamily.bold,fontSize:fontSize.lg,color:colors.onSurface},count:{minWidth:26,height:26,borderRadius:13,backgroundColor:colors.brandPrimary,alignItems:"center",justifyContent:"center"},countText:{color:colors.onBrandPrimary,fontFamily:fontFamily.bold,fontSize:fontSize.xs},search:{margin:spacing.lg,marginBottom:0,minHeight:46,flexDirection:"row",alignItems:"center",gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:colors.surface},searchInput:{flex:1,color:colors.onSurface,paddingVertical:spacing.sm},center:{flex:1,alignItems:"center",justifyContent:"center"},row:{flexDirection:"row",alignItems:"center",backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.sm,borderWidth:1,borderColor:colors.border},icon:{width:40,height:40,borderRadius:12,backgroundColor:colors.surfaceSecondary,alignItems:"center",justifyContent:"center",marginRight:spacing.md},item:{fontFamily:fontFamily.semibold,fontSize:fontSize.base,color:colors.onSurface},meta:{fontFamily:fontFamily.regular,fontSize:fontSize.sm,color:colors.muted,marginTop:3},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:8,backgroundColor:colors.surfaceSecondary},badgeText:{fontFamily:fontFamily.bold,fontSize:10,color:colors.brandPrimary},badgeLow:{backgroundColor:colors.warningSurface},badgeLowText:{color:colors.onWarning}}));
