name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: preview
