name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Configure EAS and build Android APK
    steps:
      - uses: eas/checkout
      - name: Link or create EAS project
        run: eas init --account zahoorfa72s-team --non-interactive --force
      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive --no-wait
